version: 2.1

jobs: 
  build:
    docker: 
      - image: golang:1.21
    steps:
      - checkout
      - run: go build main.go
  test:
    docker: 
      - image: golang:1.21
    steps:
      - checkout
      - run: go build main_test.go
    
workflows: 
  build_and_test:
    jobs:
      - build
      - test:
          requires: 
            - build
