version: 2.1

jobs: 
  build:
    docker: 
      - image: cimg/go:1.23
    steps:
      - checkout
      - run: main.go
  test:
    docker: 
      - image: cimg/go:1.23
    steps:
      - checkout
      - run: main.go
    
workflows: 
  build_and_test:
    jobs:
      - build
      - test:
          requires: 
            - build